### ISSUE TITLE
Switch away from DRMAA to using Snakemake Profiles

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#110]
**Is your feature request related to a problem? Please describe.**
Using cluster configuration in snakemake is deprecated. Profiles are the future.

**Describe the solution you'd like**
We should switch away from using DRMAA towards using Snakemake Profiles. In particular, the [slurm](https://github.com/Snakemake-Profiles/slurm) profile is a target.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
**Implementation Plan**

- [ ] sketch updating the workflows by updating `ngs_mapping`
- [ ] sketch updating the parallel wrappers by updating parallel mutect and dependencies
- [ ] sketch updating the overall application
- [ ] update documentation

**Comment by eudesbarbosa** [comment]
**Implement unit test for workflows with none**
- [ ] cbioportal_export
- [ ] gene_expression_report
- [ ] igv_session_generation
- [ ] ngs_data_qc
- [ ] panel_of_normals
- [ ] somatic_gene_fusion_calling
- [ ] somatic_hla_loh_calling
- [ ] somatic_purity_ploidy_estimate
- [ ] somatic_variant_annotation
- [ ] ssomatic_variant_filtration
- [ ] somatic_variant_signatures
- [ ] somatic_wgs_sv_calling
- [ ] targeted_seq_cnv_annotation
- [ ] targeted_seq_cnv_export
- [ ] targeted_seq_mei_calling
- [ ] variant_checking
- [ ] variant_combination
- [ ] variant_export
- [ ] variant_filtration
- [ ] wgs_cnv_annotation
- [ ] wgs_cnv_export
- [ ] wgs_cnv_filtration
- [ ] wgs_mei_annotation
- [ ] wgs_mei_filtration
- [ ] wgs_sv_annotation
- [ ] wgs_sv_export
- [ ] wgs_sv_filtration

**Comment by eudesbarbosa** [comment]
**Substitute update_cluster() methods**
- [ ] snappy_pipeline/workflows/cbioportal_export/__init__.py
- [ ] snappy_pipeline/workflows/gene_expression_quantification/__init__.py
- [ ] snappy_pipeline/workflows/hla_typing/__init__.py
- [ ] snappy_pipeline/workflows/ngs_data_qc/__init__.py
- [ ] snappy_pipeline/workflows/panel_of_normals/__init__.py
- [ ] snappy_pipeline/workflows/roh_calling/__init__.py
- [ ] snappy_pipeline/workflows/somatic_gene_fusion_calling/__init__.py
- [ ] snappy_pipeline/workflows/somatic_msi_calling/__init__.py
- [ ] snappy_pipeline/workflows/somatic_purity_ploidy_estimate/__init__.py
- [ ] snappy_pipeline/workflows/somatic_targeted_seq_cnv_calling/__init__.py
- [ ] snappy_pipeline/workflows/somatic_variant_annotation/__init__.py
- [ ] snappy_pipeline/workflows/somatic_variant_calling/__init__.py
- [ ] snappy_pipeline/workflows/somatic_variant_filtration/__init__.py
- [ ] snappy_pipeline/workflows/somatic_variant_signatures/__init__.py
- [ ] snappy_pipeline/workflows/somatic_wgs_cnv_calling/__init__.py
- [ ] snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py
- [ ] snappy_pipeline/workflows/targeted_seq_cnv_annotation/__init__.py
- [ ] snappy_pipeline/workflows/targeted_seq_cnv_calling/__init__.py
- [ ] snappy_pipeline/workflows/targeted_seq_cnv_export/__init__.py
- [ ] snappy_pipeline/workflows/variant_annotation/__init__.py
- [ ] snappy_pipeline/workflows/variant_calling/__init__.py
- [ ] snappy_pipeline/workflows/variant_checking/__init__.py
- [ ] snappy_pipeline/workflows/variant_combination/__init__.py
- [ ] snappy_pipeline/workflows/variant_denovo_filtration/__init__.py
- [ ] snappy_pipeline/workflows/variant_export/__init__.py
- [ ] snappy_pipeline/workflows/variant_filtration/__init__.py
- [ ] snappy_pipeline/workflows/variant_phasing/__init__.py
- [ ] snappy_pipeline/workflows/wgs_cnv_annotation/__init__.py
- [ ] snappy_pipeline/workflows/wgs_cnv_calling/__init__.py
- [ ] snappy_pipeline/workflows/wgs_cnv_export/__init__.py
- [ ] snappy_pipeline/workflows/wgs_cnv_filtration/__init__.py
- [ ] snappy_pipeline/workflows/wgs_mei_annotation/__init__.py
- [ ] snappy_pipeline/workflows/wgs_mei_calling/__init__.py
- [ ] snappy_pipeline/workflows/wgs_mei_filtration/__init__.py
- [ ] snappy_pipeline/workflows/wgs_sv_annotation/__init__.py
- [ ] snappy_pipeline/workflows/wgs_sv_calling/__init__.py
- [ ] snappy_pipeline/workflows/wgs_sv_export/__init__.py
- [ ] snappy_pipeline/workflows/wgs_sv_filtration/__init__.py
