### ISSUE TITLE
Refurbish germline processing with ONT data

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#421]
**Is your feature request related to a problem? Please describe.**
We have some code for processing of ONT long-read data.

**Describe the solution you'd like**
Make the code paths functional again and ensure that the code is up to standard with tests.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
**Implementation Steps**

- [ ] ngs_mapping
    - [ ] minimap2
    - [ ] other step parts for QC
- [ ] variant_calling
    - [ ] clair3
    - [ ] other step parts for QC
- [ ] wgs_sv_calling
    - [ ] sniffles2
- [ ] varfish_export
    - [ ] mehari, will probably need a patch
